services:
  question-db:
    image: postgres:17
    container_name: question-db
    environment:
      POSTGRES_DB: question_service
      POSTGRES_USER: peerprep
      POSTGRES_PASSWORD: peerprep_dev
    ports:
      - "5433:5432"
    volumes:
      - question-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres:17
    container_name: user-db
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: peerprep
      POSTGRES_PASSWORD: peerprep_dev
    ports:
      - "5434:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
      - ./user-service/src/database:/docker-entrypoint-initdb.d

  collaboration-db:
    image: postgres:15
    container_name: collaboration-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: peerprep
    ports:
      - "5435:5432"
    volumes:
      - collaboration_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d peerprep"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: matching-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  matching-service:
    build:
      context: ./matching-service
    container_name: matching-service
    env_file:
      - ./matching-service/.env
    environment:
      REDIS_URL: redis://matching-redis:6379
      QUESTION_SERVICE_URL: http://question-service:3003
      COLLAB_SERVICE_URL: http://host.docker.internal:3001
      # FRONTEND_URL: http://peerprep-frontend:3000
    ports:
      - "3002:3002"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  question-service:
    build:
      context: ./question-service
    container_name: question-service
    env_file:
      - ./question-service/.env
    environment:
      DATABASE_URL: postgresql://peerprep:peerprep_dev@question-db:5432/question_service
    ports:
      - "3003:3003"
    depends_on:
      - question-db
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/.env
    environment:
      DATABASE_URL: postgresql://peerprep:peerprep_dev@user-db:5432/user_service
    ports:
      - "3004:3004"
    depends_on:
      - user-db
    restart: unless-stopped

volumes:
  question-db-data:
  user-db-data:
  collaboration_db_data:
